# Generated by Django 2.0.3 on 2018-03-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_auto_20180319_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='title',
            field=models.TextField(default='Bookmark', max_length=200),
        ),
    ]
